config/routes.rb
SpChallenge::Application.routes.draw do
  get "offers/new"
  post "offers/show"
  root 'offers#new'
end

app/models/offer.rb
class Offer
  extend ActiveModel::Naming

  attr_accessor :uid, :pub0, :page, :format, :appid, :locale,
    :device_id, :timestamp, :offer_types, :hashkey

  def self.find(attributes)
    response = self.perform_request(attributes)
    if self.valid_signature?(response)
      JSON.parse(response.body)
    else
      Rails.logger.warn "Malicious response: #{response.body}" 
      { code: 'Malicious_Response'}
    end
  end

  #######
  private
  #######

  def self.api_connection
    Faraday.new(url: "http://api.sponsorpay.com/feed/v1/") do |faraday|
      # faraday.response :logger # for debugging
      faraday.use Faraday::Adapter::NetHttp
    end
  end

  def self.perform_request(attributes)
    self.api_connection.get do |req|
      req.url 'offers.' +  attributes[:format]
      attributes.tap { |hs| hs.delete(:format) }.sort_by { |k, v| k }.each do |attr|
        req.params["#{attr[0]}"] = attr[1]
      end
      req.params['hashkey'] = self.generate_hash(attributes)
    end
  end

  def self.valid_signature?(response)
    req_hash = Digest::SHA1.hexdigest(response.body + ENV['api_key']).downcase
    response['x-sponsorpay-response-signature'] == req_hash
  end

  def self.generate_hash(attributes)
    sorted_attrs = attributes.tap { |hs| hs.delete(:format) }.sort_by { |k, v| k }
    Digest::SHA1.hexdigest(URI.encode_www_form(sorted_attrs) + '&' + ENV['api_key']).downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  def new
  end

  def show
    @offers = Offer.find(offer_params)
  end

  #######
  private
  #######

  def offer_params
    params.require(:offer).permit(:uid, :pub0, :page, :locale, :appid,
                                  :device_id, :ip, :offer_types, :format, :timestamp)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpChallenge</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/offers/new.html.erb
<h1>Request offers</h1>
<%= form_for(:offer, url: offers_show_url) do |f| %>
  <%= f.label 'Uid:' %>
  <%= f.text_field :uid, required: true %>

  <%= f.label 'pub0:' %>
  <%= f.text_field :pub0 %>

  <%= f.label 'Page:' %>
  <%= f.text_field :page %>

  <%= f.hidden_field :locale, value: 'de' %>
  <%= f.hidden_field :appid, value: '157' %>
  <%= f.hidden_field :device_id, value: '2b6f0cc904d137be2e1730235f5664094b831186' %>
  <%= f.hidden_field :ip, value: '109.235.143.113' %>
  <%= f.hidden_field :offer_types, value: '112' %>
  <%= f.hidden_field :format, value: 'json' %>
  <%= f.hidden_field :timestamp, value: Time.now.to_i %>

  <%= f.submit 'Submit' %>
<% end %>

app/views/offers/show.html.erb
<h1>Current offers</h1>

<% if @offers['code'] == 'NO_CONTENT' %>
  <div class="no_offers">
    No offers
  </div>
<% elsif @offers['code'] == 'OK' %>
  <div class="offer">
    <% @offers['offers'].each do |offer| %>
      <div class='title'>Offer Title: <%= offer['title']  %></div>
      <div class='payout'>Offer Payout: <%= offer['payout']  %></div>
      <div class="thumbnail">Offer Thumbnail: <%= image_tag offer['thumbnail']['lowres'] %> </div>
    <% end%>
  </div>
<% end %>

<%= link_to 'New request', offers_new_path %>